name: 📸 Generate Snapshots
on:
    workflow_dispatch:
          
jobs:
  Generate:
    runs-on: macos-15-xlarge
    
    steps:
    - uses: actions/checkout@v4
    - uses: n1hility/cancel-previous-runs@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: 🔨 Select Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0'

    - name: 🧹 Clear existing Snapshots
      run: |
        find ./Tests/SnapshotTests -name "__Snapshots__" -exec rm -rf {} +
    - name: 📸 Generate Snapshots
      run: |
        xcodebuild test -project "${project}" -scheme "${scheme}" ${params} -destination "name=iPhone 16 Pro,OS=18.0" -destination "name=iPad (10th generation),OS=18.0" | xcpretty --utf --color && exit ${PIPESTATUS[0]}
      env:
        project: 'Adyen.xcodeproj'
        params: '-skipPackagePluginValidation'
        scheme: 'GenerateSnapshots'
        
    - name: 🚀 Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        delete-branch: true
        branch: update-snapshots-github-action
        commit-message: "🤖 Generated Snapshots"
        title: "🤖 Generate Snapshots"
        body: "Regenerate snapshots"
        token: ${{ secrets.GITHUB_TOKEN }}
